baseurl = "/"
languageCode = "en-us"
title = "Jeff Lin"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
# ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
# preserveTaxonomyNames = true
# footnotereturnlinkcontents = "↩"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

defaultContentLanguage = "en"
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.


[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]


[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A Hugo theme ported from the static site generator Ivy."
    footer = "&copy; [Yihui Xie](https://yihui.name) 2017 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"
  
  # Your details.
  name = "林建甫 Jeff Lin"
  role = "Biostatistician"
  deteFormat ="December 31, 2018"
  email = "jefflinmd38@gmail.com"

[params.logo]
    url = "NTPULogo.png"
    width = 50
    height = 50
    alt = "Logo"
